### ISSUE TITLE
TTS-Volume for about 1sec after resume

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [Supergiovane/node-red-contrib-tts-ultimate#29] opened 2021-07-05 07:07 UTC
I have some Volume issue after resume

- Main volume is 40%
- TTS volume is set to 60%
- The text is properly announced with 60
- the MAIN content resume
- the first 1-2sec of Main are with TTS volume
- after 1-2sec the volume reduces to the Main volume (40%)

This issue is not noticeable when the TTS volume is lower or equal to the Main volume

======
Using node-red-contrib-tts-ultimate 1.0.21 on Docker Node-Red V1.3.5

**Comment by Supergiovane** [comment] 2021-07-05 07:18
Hi Nexus,
yes, i'm aware of that and it will be fixed hopefully soon.
This has something to do with asyncronous calls.

**Comment by xX-Nexus-Xx** [comment] 2021-07-05 07:32
Thanks for the quick response ! looking forward to your solution

Great work

**Comment by Supergiovane** [comment] 2021-07-05 10:02
Hi
i made some changes, but i cannot try it out yet, because i'm, on holidays.
Are you able to paste a file into your node-red foder to try the fix?
You need to well know how to do this, otherwise you have to wait until i comes back to home again.

**Comment by xX-Nexus-Xx** [comment] 2021-07-05 10:29
I'm running Node-Red on a Linux Docker. Should not be a problem to paste a file for testing.

But you don't have to spoil your holiday for me. I'm happy to wait

**Comment by Supergiovane** [comment] 2021-07-05 12:36
Ok, 
Please unzip the content of this file into your .node-red/node_modules/node-red-contrib-tts-ultimate/ttsultimate folder and restart node-red.
Then try and let me know.
But before, make a copy of the old ttsultimate.js file, in case you have to restore it.
[ttsultimate.js.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/6764203/ttsultimate.js.zip)

**Comment by xX-Nexus-Xx** [comment] 2021-07-05 23:27
I replaced the file and restared Node-Red container entirely but i'm not able to hear a difference...the first 1-2sec after resume is still on the TTS volume

**Comment by Supergiovane** [comment] 2021-07-06 03:27
I must test by myself once returned at home.

**Comment by xX-Nexus-Xx** [comment] 2021-07-06 03:44
No worries, enjoy your holidays

**Comment by Supergiovane** [comment] 2021-08-24 07:39
Hi Nexus
i'm working on that... i'll le you know.

**Comment by Supergiovane** [comment] 2021-08-24 07:39
..and yes, i made 1 month holidays. :-)

**Comment by Supergiovane** [comment] 2021-08-24 08:49
Hi
Please unzip the content of this file into your **.node-red/node_modules/node-red-contrib-tts-ultimate/ttsultimate** folder and restart node-red.
Then try and let me know.

[ttsultimate.js.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/7037853/ttsultimate.js.zip)

**Comment by Supergiovane** [comment] 2021-08-24 14:47
Hi
the v. 1.0.23 is out. It should fix your issue.

**Comment by xX-Nexus-Xx** [comment] 2021-08-25 01:54
I think you sorted it out this time ;) ... well done

Initially I did a partial deploy and server restart but it did not fix the sound issue.  Only after a full-deploy and a restart of the Node-Red server it looks working now. 

I will keep monitoring and let you know if I see any weird behavior

thanks a lot for sorting this .. my wife went crazy because of these volume changes ;)

**Comment by xX-Nexus-Xx** [comment] 2021-08-25 02:39
Sorry, I was wrong :( the issue still remains.

I missed it previously as the volume of the TTS message was too close to the volume of the original content. You can check by setting the TTS volume to ~60% and the main content to about 30%-40%

**Comment by Supergiovane** [comment] 2021-08-25 03:01
Hi
The problem is, that i cannot reproduce your issue. 
What sonos device are you using?
Do you have additional players added to the list in the configuration node?
What tts service are you using? (Polly, google…)
What OS? (Windows, linux)
What’s your node version? (Please issue a node -v command in a terminal prompt)

**Comment by xX-Nexus-Xx** [comment] 2021-08-25 04:29
My test scenario is as below:
===================
- Main volume is 40% (Sound from TV via Sonos-Beam)
- TTS volume is set to 60% (Node-Red announcement via Sonos-Beam)
- The text is properly announced with 60% volume
- the MAIN content resume 
- the first 1-2sec of Main are with TTS volume (TV sound but with 60% volume from TTS)
- after 1-2sec the volume reduces to the Main volume (TV sound back to 40%)
- This issue is not noticeable when the TTS volume is lower or equal to the Main volume

======
Using node-red-contrib-tts-ultimate 1.0.23 on Ubuntu Docker Node-Red V2.0.1
I have a Sonos-Beam at the TV (this is where I checked for the issues) additionally I have 2xSonos5 and several Sonos1
I'm using the Amazon-Polly TTS (with the default Joanna voice) no other players are defined in the config
![image](https://user-images.githubusercontent.com/2195190/130725126-149deaf4-bc55-449e-bd08-2514ae7e5c9b.png)
![image](https://user-images.githubusercontent.com/2195190/130725185-931ecaa1-97f5-4be6-91f4-7ac35b110be4.png)

**Comment by Supergiovane** [comment] 2021-08-25 04:34
Thank you. 
is the tv sending audio to the sonos beam, via tha HDMI audio return channel?

**Comment by xX-Nexus-Xx** [comment] 2021-08-25 04:57
Yes, the sound from TV is via HDMI to Sonos-Beam

**Comment by Supergiovane** [comment] 2021-08-25 05:20
Hi,
Please unzip the content of this file into your **.node-red/node_modules/node-red-contrib-tts-ultimate/ttsultimate** folder and restart node-red.
Then try and let me know.
I'm proceeding in the blind, because i've no beam to test with.

[ttsultimate.js.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/7043869/ttsultimate.js.zip)

**Comment by xX-Nexus-Xx** [comment] 2021-08-25 06:42
hmm... on a first test it looks sorted .. let me monitor for 1-2days

**Comment by Supergiovane** [comment] 2021-08-25 06:48
Good.
Sorted ot that maybe there was a sync function, not really sync. Please use this file, i made some more adjustments.
Thanks.
[ttsultimate.js.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/7044271/ttsultimate.js.zip)

**Comment by xX-Nexus-Xx** [comment] 2021-08-28 07:01
it works !! ... thx a lot

**Closed** 2021-08-28 07:01 UTC

**Comment by Supergiovane** [comment] 2021-08-28 07:18
Thanks. Cheers!
